apiVersion: v1
kind: Service
metadata:
  name: backend-feed-service
  labels:
    app: backend-feed-service
spec: 
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-feed-service