apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec: 
  ports:
    - name: "8080"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend-service