apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec: 
  ports:
    - name: "8080"
      port: 8100
      targetPort: 8100
      protocol: TCP
  selector:
    app: frontend