name: udagram-ci
on: 
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build Docker images
        run: docker-compose -f docker-compose-build.yaml build --paralle

      - name: List Docker images
        run: docker images

      - name: Push Docker images
        run: |
          docker tag reverseproxy ${{ secrets.DOCKERHUB_USERNAME }}/reverseproxy:reverseproxy-v2
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reverseproxy:reverseproxy-v2
          docker tag udagram-api-user ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-user:udagram-api-user
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-user:udagram-api-user
          docker tag udagram-api-feed ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:udagram-api-feed
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:udagram-api-feed
          docker tag udagram-frontend ${{ secrets.DOCKERHUB_USERNAME }}/udagram-frontend:udagram-frontend-v2
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/udagram-frontend:udagram-frontend-v2